//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferensimplementationPersonsok.SparServiceReference {


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://skatteverket.se/spar/instans/1.0", ConfigurationName="SparServiceReference.SPARPersonsokning")]
    public interface SPARPersonsokning {

        // CODEGEN: Generating message contract since the operation SPARPersonsokning is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar1 SPARPersonsokning(ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga1 request);

        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar1> SPARPersonsokningAsync(ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga1 request);

        // CODEGEN: Generating message contract since the operation Personsokning is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Personsokning(ReferensimplementationPersonsok.SparServiceReference.PersonsokningFraga request);

        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task PersonsokningAsync(ReferensimplementationPersonsok.SparServiceReference.PersonsokningFraga request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://skatteverket.se/spar/instans/1.0")]
    public partial class SPARPersonsokningFraga : object, System.ComponentModel.INotifyPropertyChanged {

        private IdentifieringsInformationTYPE identifieringsInformationField;

        private PersonsokningFragaTYPE personsokningFragaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0", Order=0)]
        public IdentifieringsInformationTYPE IdentifieringsInformation {
            get {
                return this.identifieringsInformationField;
            }
            set {
                this.identifieringsInformationField = value;
                this.RaisePropertyChanged("IdentifieringsInformation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0", Order=1)]
        public PersonsokningFragaTYPE PersonsokningFraga {
            get {
                return this.personsokningFragaField;
            }
            set {
                this.personsokningFragaField = value;
                this.RaisePropertyChanged("PersonsokningFraga");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class IdentifieringsInformationTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private int kundNrLeveransMottagareField;

        private int kundNrSlutkundField;

        private string orgNrSlutkundField;

        private long uppdragsIdField;

        private bool uppdragsIdFieldSpecified;

        private string slutAnvandarIdField;

        private SlutAnvandarUtokadBehorighetTYPE[] slutAnvandarUtokadBehorighetField;

        private System.DateTime tidsstampelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int KundNrLeveransMottagare {
            get {
                return this.kundNrLeveransMottagareField;
            }
            set {
                this.kundNrLeveransMottagareField = value;
                this.RaisePropertyChanged("KundNrLeveransMottagare");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int KundNrSlutkund {
            get {
                return this.kundNrSlutkundField;
            }
            set {
                this.kundNrSlutkundField = value;
                this.RaisePropertyChanged("KundNrSlutkund");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrgNrSlutkund {
            get {
                return this.orgNrSlutkundField;
            }
            set {
                this.orgNrSlutkundField = value;
                this.RaisePropertyChanged("OrgNrSlutkund");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long UppdragsId {
            get {
                return this.uppdragsIdField;
            }
            set {
                this.uppdragsIdField = value;
                this.RaisePropertyChanged("UppdragsId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UppdragsIdSpecified {
            get {
                return this.uppdragsIdFieldSpecified;
            }
            set {
                this.uppdragsIdFieldSpecified = value;
                this.RaisePropertyChanged("UppdragsIdSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SlutAnvandarId {
            get {
                return this.slutAnvandarIdField;
            }
            set {
                this.slutAnvandarIdField = value;
                this.RaisePropertyChanged("SlutAnvandarId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SlutAnvandarUtokadBehorighet", Order=5)]
        public SlutAnvandarUtokadBehorighetTYPE[] SlutAnvandarUtokadBehorighet {
            get {
                return this.slutAnvandarUtokadBehorighetField;
            }
            set {
                this.slutAnvandarUtokadBehorighetField = value;
                this.RaisePropertyChanged("SlutAnvandarUtokadBehorighet");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Tidsstampel {
            get {
                return this.tidsstampelField;
            }
            set {
                this.tidsstampelField = value;
                this.RaisePropertyChanged("Tidsstampel");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum SlutAnvandarUtokadBehorighetTYPE {

        /// <remarks/>
        Relationer,

        /// <remarks/>
        Medborgarskap,

        /// <remarks/>
        Taxering,

        /// <remarks/>
        Sekretess,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class OverstigerMaxAntalSvarsposterTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private int antalPosterField;

        private int maxAntalSvarsPosterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AntalPoster {
            get {
                return this.antalPosterField;
            }
            set {
                this.antalPosterField = value;
                this.RaisePropertyChanged("AntalPoster");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MaxAntalSvarsPoster {
            get {
                return this.maxAntalSvarsPosterField;
            }
            set {
                this.maxAntalSvarsPosterField = value;
                this.RaisePropertyChanged("MaxAntalSvarsPoster");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class UndantagTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private string kodField;

        private string beskrivningField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("Kod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Beskrivning {
            get {
                return this.beskrivningField;
            }
            set {
                this.beskrivningField = value;
                this.RaisePropertyChanged("Beskrivning");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class FastighetTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private string fastighetLanKodField;

        private string fastighetKommunKodField;

        private FastighetsKodTYPE fastighetsKodField;

        private string andelstalTaljareField;

        private string andelstalNamnareField;

        private string taxeringsarField;

        private string taxeringsvardeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FastighetLanKod {
            get {
                return this.fastighetLanKodField;
            }
            set {
                this.fastighetLanKodField = value;
                this.RaisePropertyChanged("FastighetLanKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FastighetKommunKod {
            get {
                return this.fastighetKommunKodField;
            }
            set {
                this.fastighetKommunKodField = value;
                this.RaisePropertyChanged("FastighetKommunKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FastighetsKodTYPE FastighetsKod {
            get {
                return this.fastighetsKodField;
            }
            set {
                this.fastighetsKodField = value;
                this.RaisePropertyChanged("FastighetsKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string AndelstalTaljare {
            get {
                return this.andelstalTaljareField;
            }
            set {
                this.andelstalTaljareField = value;
                this.RaisePropertyChanged("AndelstalTaljare");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string AndelstalNamnare {
            get {
                return this.andelstalNamnareField;
            }
            set {
                this.andelstalNamnareField = value;
                this.RaisePropertyChanged("AndelstalNamnare");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Taxeringsar {
            get {
                return this.taxeringsarField;
            }
            set {
                this.taxeringsarField = value;
                this.RaisePropertyChanged("Taxeringsar");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Taxeringsvarde {
            get {
                return this.taxeringsvardeField;
            }
            set {
                this.taxeringsvardeField = value;
                this.RaisePropertyChanged("Taxeringsvarde");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum FastighetsKodTYPE {

        /// <remarks/>
        S,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class RelationTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private System.DateTime datumFromField;

        private System.DateTime datumTillField;

        private RelationstypTYPE relationstypField;

        private PersonIdTYPE personIdField;

        private string fornamnField;

        private string mellannamnField;

        private string efternamnField;

        private System.DateTime fodelsetidField;

        private bool fodelsetidFieldSpecified;

        private AvregistreringsorsakKodTYPE avregistreringsorsakKodField;

        private bool avregistreringsorsakKodFieldSpecified;

        private string avregistreringsdatumField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumFrom {
            get {
                return this.datumFromField;
            }
            set {
                this.datumFromField = value;
                this.RaisePropertyChanged("DatumFrom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumTill {
            get {
                return this.datumTillField;
            }
            set {
                this.datumTillField = value;
                this.RaisePropertyChanged("DatumTill");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationstypTYPE Relationstyp {
            get {
                return this.relationstypField;
            }
            set {
                this.relationstypField = value;
                this.RaisePropertyChanged("Relationstyp");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PersonIdTYPE PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("PersonId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Fornamn {
            get {
                return this.fornamnField;
            }
            set {
                this.fornamnField = value;
                this.RaisePropertyChanged("Fornamn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Mellannamn {
            get {
                return this.mellannamnField;
            }
            set {
                this.mellannamnField = value;
                this.RaisePropertyChanged("Mellannamn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Efternamn {
            get {
                return this.efternamnField;
            }
            set {
                this.efternamnField = value;
                this.RaisePropertyChanged("Efternamn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime Fodelsetid {
            get {
                return this.fodelsetidField;
            }
            set {
                this.fodelsetidField = value;
                this.RaisePropertyChanged("Fodelsetid");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FodelsetidSpecified {
            get {
                return this.fodelsetidFieldSpecified;
            }
            set {
                this.fodelsetidFieldSpecified = value;
                this.RaisePropertyChanged("FodelsetidSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public AvregistreringsorsakKodTYPE AvregistreringsorsakKod {
            get {
                return this.avregistreringsorsakKodField;
            }
            set {
                this.avregistreringsorsakKodField = value;
                this.RaisePropertyChanged("AvregistreringsorsakKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvregistreringsorsakKodSpecified {
            get {
                return this.avregistreringsorsakKodFieldSpecified;
            }
            set {
                this.avregistreringsorsakKodFieldSpecified = value;
                this.RaisePropertyChanged("AvregistreringsorsakKodSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Avregistreringsdatum {
            get {
                return this.avregistreringsdatumField;
            }
            set {
                this.avregistreringsdatumField = value;
                this.RaisePropertyChanged("Avregistreringsdatum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum RelationstypTYPE {

        /// <remarks/>
        V,

        /// <remarks/>
        M,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class PersonIdTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private string fysiskPersonIdField;

        private NulageTYPE nulageField;

        public PersonIdTYPE() {
            this.nulageField = NulageTYPE.N;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FysiskPersonId {
            get {
                return this.fysiskPersonIdField;
            }
            set {
                this.fysiskPersonIdField = value;
                this.RaisePropertyChanged("FysiskPersonId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(NulageTYPE.N)]
        public NulageTYPE nulage {
            get {
                return this.nulageField;
            }
            set {
                this.nulageField = value;
                this.RaisePropertyChanged("nulage");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum NulageTYPE {

        /// <remarks/>
        J,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum AvregistreringsorsakKodTYPE {

        /// <remarks/>
        A,

        /// <remarks/>
        G,

        /// <remarks/>
        O,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class UtlandsadressTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private System.DateTime datumFromField;

        private System.DateTime datumTillField;

        private string careOfField;

        private string utdelningsadress1Field;

        private string utdelningsadress2Field;

        private string utdelningsadress3Field;

        private string landField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumFrom {
            get {
                return this.datumFromField;
            }
            set {
                this.datumFromField = value;
                this.RaisePropertyChanged("DatumFrom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumTill {
            get {
                return this.datumTillField;
            }
            set {
                this.datumTillField = value;
                this.RaisePropertyChanged("DatumTill");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CareOf {
            get {
                return this.careOfField;
            }
            set {
                this.careOfField = value;
                this.RaisePropertyChanged("CareOf");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Utdelningsadress1 {
            get {
                return this.utdelningsadress1Field;
            }
            set {
                this.utdelningsadress1Field = value;
                this.RaisePropertyChanged("Utdelningsadress1");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Utdelningsadress2 {
            get {
                return this.utdelningsadress2Field;
            }
            set {
                this.utdelningsadress2Field = value;
                this.RaisePropertyChanged("Utdelningsadress2");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Utdelningsadress3 {
            get {
                return this.utdelningsadress3Field;
            }
            set {
                this.utdelningsadress3Field = value;
                this.RaisePropertyChanged("Utdelningsadress3");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
                this.RaisePropertyChanged("Land");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class SarskildPostadressTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private System.DateTime datumFromField;

        private System.DateTime datumTillField;

        private string careOfField;

        private string utdelningsadress1Field;

        private string utdelningsadress2Field;

        private string postNrField;

        private string postortField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumFrom {
            get {
                return this.datumFromField;
            }
            set {
                this.datumFromField = value;
                this.RaisePropertyChanged("DatumFrom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumTill {
            get {
                return this.datumTillField;
            }
            set {
                this.datumTillField = value;
                this.RaisePropertyChanged("DatumTill");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CareOf {
            get {
                return this.careOfField;
            }
            set {
                this.careOfField = value;
                this.RaisePropertyChanged("CareOf");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Utdelningsadress1 {
            get {
                return this.utdelningsadress1Field;
            }
            set {
                this.utdelningsadress1Field = value;
                this.RaisePropertyChanged("Utdelningsadress1");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Utdelningsadress2 {
            get {
                return this.utdelningsadress2Field;
            }
            set {
                this.utdelningsadress2Field = value;
                this.RaisePropertyChanged("Utdelningsadress2");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PostNr {
            get {
                return this.postNrField;
            }
            set {
                this.postNrField = value;
                this.RaisePropertyChanged("PostNr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Postort {
            get {
                return this.postortField;
            }
            set {
                this.postortField = value;
                this.RaisePropertyChanged("Postort");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class FolkbokforingsadressTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private System.DateTime datumFromField;

        private System.DateTime datumTillField;

        private string careOfField;

        private string utdelningsadress1Field;

        private string utdelningsadress2Field;

        private string postNrField;

        private string postortField;

        private string folkbokfordLanKodField;

        private string folkbokfordKommunKodField;

        private string folkbokfordForsamlingKodField;

        private System.DateTime folkbokforingsdatumField;

        private bool folkbokforingsdatumFieldSpecified;

        private string distriktKodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumFrom {
            get {
                return this.datumFromField;
            }
            set {
                this.datumFromField = value;
                this.RaisePropertyChanged("DatumFrom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumTill {
            get {
                return this.datumTillField;
            }
            set {
                this.datumTillField = value;
                this.RaisePropertyChanged("DatumTill");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CareOf {
            get {
                return this.careOfField;
            }
            set {
                this.careOfField = value;
                this.RaisePropertyChanged("CareOf");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Utdelningsadress1 {
            get {
                return this.utdelningsadress1Field;
            }
            set {
                this.utdelningsadress1Field = value;
                this.RaisePropertyChanged("Utdelningsadress1");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Utdelningsadress2 {
            get {
                return this.utdelningsadress2Field;
            }
            set {
                this.utdelningsadress2Field = value;
                this.RaisePropertyChanged("Utdelningsadress2");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PostNr {
            get {
                return this.postNrField;
            }
            set {
                this.postNrField = value;
                this.RaisePropertyChanged("PostNr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Postort {
            get {
                return this.postortField;
            }
            set {
                this.postortField = value;
                this.RaisePropertyChanged("Postort");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FolkbokfordLanKod {
            get {
                return this.folkbokfordLanKodField;
            }
            set {
                this.folkbokfordLanKodField = value;
                this.RaisePropertyChanged("FolkbokfordLanKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FolkbokfordKommunKod {
            get {
                return this.folkbokfordKommunKodField;
            }
            set {
                this.folkbokfordKommunKodField = value;
                this.RaisePropertyChanged("FolkbokfordKommunKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FolkbokfordForsamlingKod {
            get {
                return this.folkbokfordForsamlingKodField;
            }
            set {
                this.folkbokfordForsamlingKodField = value;
                this.RaisePropertyChanged("FolkbokfordForsamlingKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime Folkbokforingsdatum {
            get {
                return this.folkbokforingsdatumField;
            }
            set {
                this.folkbokforingsdatumField = value;
                this.RaisePropertyChanged("Folkbokforingsdatum");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FolkbokforingsdatumSpecified {
            get {
                return this.folkbokforingsdatumFieldSpecified;
            }
            set {
                this.folkbokforingsdatumFieldSpecified = value;
                this.RaisePropertyChanged("FolkbokforingsdatumSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DistriktKod {
            get {
                return this.distriktKodField;
            }
            set {
                this.distriktKodField = value;
                this.RaisePropertyChanged("DistriktKod");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class AdresserTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private FolkbokforingsadressTYPE[] folkbokforingsadressField;

        private SarskildPostadressTYPE[] sarskildPostadressField;

        private UtlandsadressTYPE[] utlandsadressField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folkbokforingsadress", Order=0)]
        public FolkbokforingsadressTYPE[] Folkbokforingsadress {
            get {
                return this.folkbokforingsadressField;
            }
            set {
                this.folkbokforingsadressField = value;
                this.RaisePropertyChanged("Folkbokforingsadress");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SarskildPostadress", Order=1)]
        public SarskildPostadressTYPE[] SarskildPostadress {
            get {
                return this.sarskildPostadressField;
            }
            set {
                this.sarskildPostadressField = value;
                this.RaisePropertyChanged("SarskildPostadress");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Utlandsadress", Order=2)]
        public UtlandsadressTYPE[] Utlandsadress {
            get {
                return this.utlandsadressField;
            }
            set {
                this.utlandsadressField = value;
                this.RaisePropertyChanged("Utlandsadress");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class PersondetaljerTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private System.DateTime datumFromField;

        private System.DateTime datumTillField;

        private string aviseringsnamnField;

        private string fornamnField;

        private int tilltalsnamnField;

        private bool tilltalsnamnFieldSpecified;

        private string mellannamnField;

        private string efternamnField;

        private SekretessmarkeringTYPE sekretessmarkeringField;

        private bool sekretessmarkeringFieldSpecified;

        private AvregistreringsorsakKodTYPE avregistreringsorsakKodField;

        private bool avregistreringsorsakKodFieldSpecified;

        private string avregistreringsdatumField;

        private string hanvisningsPersonNrByttFranField;

        private string hanvisningsPersonNrByttTillField;

        private System.DateTime fodelsetidField;

        private bool fodelsetidFieldSpecified;

        private string fodelselanKodField;

        private string fodelseforsamlingField;

        private KonTYPE konField;

        private bool konFieldSpecified;

        private SvenskMedborgareTYPE svenskMedborgareField;

        private bool svenskMedborgareFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumFrom {
            get {
                return this.datumFromField;
            }
            set {
                this.datumFromField = value;
                this.RaisePropertyChanged("DatumFrom");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumTill {
            get {
                return this.datumTillField;
            }
            set {
                this.datumTillField = value;
                this.RaisePropertyChanged("DatumTill");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Aviseringsnamn {
            get {
                return this.aviseringsnamnField;
            }
            set {
                this.aviseringsnamnField = value;
                this.RaisePropertyChanged("Aviseringsnamn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Fornamn {
            get {
                return this.fornamnField;
            }
            set {
                this.fornamnField = value;
                this.RaisePropertyChanged("Fornamn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Tilltalsnamn {
            get {
                return this.tilltalsnamnField;
            }
            set {
                this.tilltalsnamnField = value;
                this.RaisePropertyChanged("Tilltalsnamn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TilltalsnamnSpecified {
            get {
                return this.tilltalsnamnFieldSpecified;
            }
            set {
                this.tilltalsnamnFieldSpecified = value;
                this.RaisePropertyChanged("TilltalsnamnSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Mellannamn {
            get {
                return this.mellannamnField;
            }
            set {
                this.mellannamnField = value;
                this.RaisePropertyChanged("Mellannamn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Efternamn {
            get {
                return this.efternamnField;
            }
            set {
                this.efternamnField = value;
                this.RaisePropertyChanged("Efternamn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public SekretessmarkeringTYPE Sekretessmarkering {
            get {
                return this.sekretessmarkeringField;
            }
            set {
                this.sekretessmarkeringField = value;
                this.RaisePropertyChanged("Sekretessmarkering");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SekretessmarkeringSpecified {
            get {
                return this.sekretessmarkeringFieldSpecified;
            }
            set {
                this.sekretessmarkeringFieldSpecified = value;
                this.RaisePropertyChanged("SekretessmarkeringSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public AvregistreringsorsakKodTYPE AvregistreringsorsakKod {
            get {
                return this.avregistreringsorsakKodField;
            }
            set {
                this.avregistreringsorsakKodField = value;
                this.RaisePropertyChanged("AvregistreringsorsakKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvregistreringsorsakKodSpecified {
            get {
                return this.avregistreringsorsakKodFieldSpecified;
            }
            set {
                this.avregistreringsorsakKodFieldSpecified = value;
                this.RaisePropertyChanged("AvregistreringsorsakKodSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Avregistreringsdatum {
            get {
                return this.avregistreringsdatumField;
            }
            set {
                this.avregistreringsdatumField = value;
                this.RaisePropertyChanged("Avregistreringsdatum");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string HanvisningsPersonNrByttFran {
            get {
                return this.hanvisningsPersonNrByttFranField;
            }
            set {
                this.hanvisningsPersonNrByttFranField = value;
                this.RaisePropertyChanged("HanvisningsPersonNrByttFran");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string HanvisningsPersonNrByttTill {
            get {
                return this.hanvisningsPersonNrByttTillField;
            }
            set {
                this.hanvisningsPersonNrByttTillField = value;
                this.RaisePropertyChanged("HanvisningsPersonNrByttTill");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=12)]
        public System.DateTime Fodelsetid {
            get {
                return this.fodelsetidField;
            }
            set {
                this.fodelsetidField = value;
                this.RaisePropertyChanged("Fodelsetid");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FodelsetidSpecified {
            get {
                return this.fodelsetidFieldSpecified;
            }
            set {
                this.fodelsetidFieldSpecified = value;
                this.RaisePropertyChanged("FodelsetidSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FodelselanKod {
            get {
                return this.fodelselanKodField;
            }
            set {
                this.fodelselanKodField = value;
                this.RaisePropertyChanged("FodelselanKod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Fodelseforsamling {
            get {
                return this.fodelseforsamlingField;
            }
            set {
                this.fodelseforsamlingField = value;
                this.RaisePropertyChanged("Fodelseforsamling");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public KonTYPE Kon {
            get {
                return this.konField;
            }
            set {
                this.konField = value;
                this.RaisePropertyChanged("Kon");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KonSpecified {
            get {
                return this.konFieldSpecified;
            }
            set {
                this.konFieldSpecified = value;
                this.RaisePropertyChanged("KonSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public SvenskMedborgareTYPE SvenskMedborgare {
            get {
                return this.svenskMedborgareField;
            }
            set {
                this.svenskMedborgareField = value;
                this.RaisePropertyChanged("SvenskMedborgare");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SvenskMedborgareSpecified {
            get {
                return this.svenskMedborgareFieldSpecified;
            }
            set {
                this.svenskMedborgareFieldSpecified = value;
                this.RaisePropertyChanged("SvenskMedborgareSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum SekretessmarkeringTYPE {

        /// <remarks/>
        J,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum KonTYPE {

        /// <remarks/>
        M,

        /// <remarks/>
        K,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum SvenskMedborgareTYPE {

        /// <remarks/>
        J,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class AviseringsPostTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private PersonIdTYPE personIdField;

        private SekretessmarkeringTYPE sekretessmarkeringField;

        private System.DateTime sekretessAndringsdatumField;

        private bool sekretessAndringsdatumFieldSpecified;

        private System.DateTime senasteAndringSPARField;

        private bool senasteAndringSPARFieldSpecified;

        private string summeradInkomstField;

        private string beskattningsarField;

        private PersondetaljerTYPE[] persondetaljerField;

        private AdresserTYPE adresserField;

        private RelationTYPE[] relationField;

        private FastighetTYPE[] fastighetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonIdTYPE PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
                this.RaisePropertyChanged("PersonId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SekretessmarkeringTYPE Sekretessmarkering {
            get {
                return this.sekretessmarkeringField;
            }
            set {
                this.sekretessmarkeringField = value;
                this.RaisePropertyChanged("Sekretessmarkering");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime SekretessAndringsdatum {
            get {
                return this.sekretessAndringsdatumField;
            }
            set {
                this.sekretessAndringsdatumField = value;
                this.RaisePropertyChanged("SekretessAndringsdatum");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SekretessAndringsdatumSpecified {
            get {
                return this.sekretessAndringsdatumFieldSpecified;
            }
            set {
                this.sekretessAndringsdatumFieldSpecified = value;
                this.RaisePropertyChanged("SekretessAndringsdatumSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime SenasteAndringSPAR {
            get {
                return this.senasteAndringSPARField;
            }
            set {
                this.senasteAndringSPARField = value;
                this.RaisePropertyChanged("SenasteAndringSPAR");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SenasteAndringSPARSpecified {
            get {
                return this.senasteAndringSPARFieldSpecified;
            }
            set {
                this.senasteAndringSPARFieldSpecified = value;
                this.RaisePropertyChanged("SenasteAndringSPARSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SummeradInkomst {
            get {
                return this.summeradInkomstField;
            }
            set {
                this.summeradInkomstField = value;
                this.RaisePropertyChanged("SummeradInkomst");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Beskattningsar {
            get {
                return this.beskattningsarField;
            }
            set {
                this.beskattningsarField = value;
                this.RaisePropertyChanged("Beskattningsar");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Persondetaljer", Order=6)]
        public PersondetaljerTYPE[] Persondetaljer {
            get {
                return this.persondetaljerField;
            }
            set {
                this.persondetaljerField = value;
                this.RaisePropertyChanged("Persondetaljer");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public AdresserTYPE Adresser {
            get {
                return this.adresserField;
            }
            set {
                this.adresserField = value;
                this.RaisePropertyChanged("Adresser");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relation", Order=8)]
        public RelationTYPE[] Relation {
            get {
                return this.relationField;
            }
            set {
                this.relationField = value;
                this.RaisePropertyChanged("Relation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fastighet", Order=9)]
        public FastighetTYPE[] Fastighet {
            get {
                return this.fastighetField;
            }
            set {
                this.fastighetField = value;
                this.RaisePropertyChanged("Fastighet");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public partial class PersonsokningFragaTYPE : object, System.ComponentModel.INotifyPropertyChanged {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DistriktKod", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DistriktKodFrom", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DistriktKodTom", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Fodelsetid", typeof(System.DateTime), DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FodelsetidFran", typeof(System.DateTime), DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FodelsetidTill", typeof(System.DateTime), DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FonetiskSokning", typeof(FonetiskSokningTYPE), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FornamnSokArgument", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ForsamlingKod", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KommunKod", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Kon", typeof(KonTYPE), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LanKod", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MellanEfternamnSokArgument", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NamnSokArgument", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PersonId", typeof(PersonIdTYPE), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PostNr", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PostNrFran", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PostNrTill", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PostortSokArgument", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UtdelningsadressSokArgument", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0")]
    public enum FonetiskSokningTYPE {

        /// <remarks/>
        J,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0", IncludeInSchema=false)]
    public enum ItemsChoiceType {

        /// <remarks/>
        DistriktKod,

        /// <remarks/>
        DistriktKodFrom,

        /// <remarks/>
        DistriktKodTom,

        /// <remarks/>
        Fodelsetid,

        /// <remarks/>
        FodelsetidFran,

        /// <remarks/>
        FodelsetidTill,

        /// <remarks/>
        FonetiskSokning,

        /// <remarks/>
        FornamnSokArgument,

        /// <remarks/>
        ForsamlingKod,

        /// <remarks/>
        KommunKod,

        /// <remarks/>
        Kon,

        /// <remarks/>
        LanKod,

        /// <remarks/>
        MellanEfternamnSokArgument,

        /// <remarks/>
        NamnSokArgument,

        /// <remarks/>
        PersonId,

        /// <remarks/>
        PostNr,

        /// <remarks/>
        PostNrFran,

        /// <remarks/>
        PostNrTill,

        /// <remarks/>
        PostortSokArgument,

        /// <remarks/>
        UtdelningsadressSokArgument,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://skatteverket.se/spar/instans/1.0")]
    public partial class SPARPersonsokningSvar : object, System.ComponentModel.INotifyPropertyChanged {

        private PersonsokningFragaTYPE personsokningFragaField;

        private AviseringsPostTYPE[] personsokningSvarsPostField;

        private UndantagTYPE[] undantagField;

        private OverstigerMaxAntalSvarsposterTYPE overstigerMaxAntalSvarsposterField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0", Order=0)]
        public PersonsokningFragaTYPE PersonsokningFraga {
            get {
                return this.personsokningFragaField;
            }
            set {
                this.personsokningFragaField = value;
                this.RaisePropertyChanged("PersonsokningFraga");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonsokningSvarsPost", Namespace="http://skatteverket.se/spar/komponent/1.0", Order=1)]
        public AviseringsPostTYPE[] PersonsokningSvarsPost {
            get {
                return this.personsokningSvarsPostField;
            }
            set {
                this.personsokningSvarsPostField = value;
                this.RaisePropertyChanged("PersonsokningSvarsPost");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Undantag", Namespace="http://skatteverket.se/spar/komponent/1.0", Order=2)]
        public UndantagTYPE[] Undantag {
            get {
                return this.undantagField;
            }
            set {
                this.undantagField = value;
                this.RaisePropertyChanged("Undantag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://skatteverket.se/spar/komponent/1.0", Order=3)]
        public OverstigerMaxAntalSvarsposterTYPE OverstigerMaxAntalSvarsposter {
            get {
                return this.overstigerMaxAntalSvarsposterField;
            }
            set {
                this.overstigerMaxAntalSvarsposterField = value;
                this.RaisePropertyChanged("OverstigerMaxAntalSvarsposter");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SPARPersonsokningFraga1 {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://skatteverket.se/spar/instans/1.0", Order=0)]
        public ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga SPARPersonsokningFraga;

        public SPARPersonsokningFraga1() {
        }

        public SPARPersonsokningFraga1(ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga SPARPersonsokningFraga) {
            this.SPARPersonsokningFraga = SPARPersonsokningFraga;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SPARPersonsokningSvar1 {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://skatteverket.se/spar/instans/1.0", Order=0)]
        public ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar SPARPersonsokningSvar;

        public SPARPersonsokningSvar1() {
        }

        public SPARPersonsokningSvar1(ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar SPARPersonsokningSvar) {
            this.SPARPersonsokningSvar = SPARPersonsokningSvar;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonsokningFraga {

        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersonsokningFraga", Namespace="http://skatteverket.se/spar/komponent/1.0", Order=0)]
        public ReferensimplementationPersonsok.SparServiceReference.PersonsokningFragaTYPE PersonsokningFraga1;

        public PersonsokningFraga() {
        }

        public PersonsokningFraga(ReferensimplementationPersonsok.SparServiceReference.PersonsokningFragaTYPE PersonsokningFraga1) {
            this.PersonsokningFraga1 = PersonsokningFraga1;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SPARPersonsokningChannel : ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPARPersonsokningClient : System.ServiceModel.ClientBase<ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning>, ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning {

        public SPARPersonsokningClient() {
        }

        public SPARPersonsokningClient(string endpointConfigurationName) :
                base(endpointConfigurationName) {
        }

        public SPARPersonsokningClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public SPARPersonsokningClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress) {
        }

        public SPARPersonsokningClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress) {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar1 ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning.SPARPersonsokning(ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga1 request) {
            return base.Channel.SPARPersonsokning(request);
        }

        public ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar SPARPersonsokning(ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga SPARPersonsokningFraga) {
            ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga1 inValue = new ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga1();
            inValue.SPARPersonsokningFraga = SPARPersonsokningFraga;
            ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar1 retVal = ((ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning)(this)).SPARPersonsokning(inValue);
            return retVal.SPARPersonsokningSvar;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar1> ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning.SPARPersonsokningAsync(ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga1 request) {
            return base.Channel.SPARPersonsokningAsync(request);
        }

        public System.Threading.Tasks.Task<ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningSvar1> SPARPersonsokningAsync(ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga SPARPersonsokningFraga) {
            ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga1 inValue = new ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokningFraga1();
            inValue.SPARPersonsokningFraga = SPARPersonsokningFraga;
            return ((ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning)(this)).SPARPersonsokningAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning.Personsokning(ReferensimplementationPersonsok.SparServiceReference.PersonsokningFraga request) {
            base.Channel.Personsokning(request);
        }

        public void Personsokning(ReferensimplementationPersonsok.SparServiceReference.PersonsokningFragaTYPE PersonsokningFraga1) {
            ReferensimplementationPersonsok.SparServiceReference.PersonsokningFraga inValue = new ReferensimplementationPersonsok.SparServiceReference.PersonsokningFraga();
            inValue.PersonsokningFraga1 = PersonsokningFraga1;
            ((ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning)(this)).Personsokning(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning.PersonsokningAsync(ReferensimplementationPersonsok.SparServiceReference.PersonsokningFraga request) {
            return base.Channel.PersonsokningAsync(request);
        }

        public System.Threading.Tasks.Task PersonsokningAsync(ReferensimplementationPersonsok.SparServiceReference.PersonsokningFragaTYPE PersonsokningFraga1) {
            ReferensimplementationPersonsok.SparServiceReference.PersonsokningFraga inValue = new ReferensimplementationPersonsok.SparServiceReference.PersonsokningFraga();
            inValue.PersonsokningFraga1 = PersonsokningFraga1;
            return ((ReferensimplementationPersonsok.SparServiceReference.SPARPersonsokning)(this)).PersonsokningAsync(inValue);
        }
    }
}
